apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: devops-final-exercise-day
labels:
  app.kubernetes.io/name: devops-final-exercise-day
  app.kubernetes.io/instance: devops-final-exercise-day-master
  app.kubernetes.io/part-of: devops-final-exercise-day
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: devops-final-exercise-day
    spec:
      output:
        pushSecret:
          name: artifactory
        to:
          kind: DockerImage
          name: prj-elcavn-training-docker.artifactory.svc.elca.ch/devops-final-exercise-day:lasted
      source:
        type: Binary
      strategy:
        type: Docker
      resources:
        requests:
          cpu: "250m"
          memory: "2Gi"
        limits:
          cpu: "4"
          memory: "4Gi"