apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: petclinic-deploy
labels:
  app.kubernetes.io/name: petclinic
  app.kubernetes.io/instance: petclinic-main
  app.kubernetes.io/part-of: petclinic
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: petclinic
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/instance: petclinic-main
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: petclinic-main
          annotations:
            containerid: ${CONTAINER_ID}
        spec:
          containers:
            - name: petclinic
              image: prj-elcavn-training-docker.artifactory.svc.elca.ch/petclinic:day
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: '1'
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 2Gi
              startupProbe:
                exec:
                  command:
                    - /bin/bash
                    - '-c'
                    - curl -s localhost:9000/api/system/status | grep '"status":"UP"'
                periodSeconds: 10
                failureThreshold: 25
                successThreshold: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/bash
                    - '-c'
                    - curl -s localhost:9000/api/system/status | grep '"status":"UP"'
                periodSeconds: 10
                failureThreshold: 3
                successThreshold: 1
              livenessProbe:
                exec:
                  command:
                    - /bin/bash
                    - '-c'
                    - curl -s localhost:9000/api/system/status | grep '"status":"UP"'
                periodSeconds: 10
                failureThreshold: 10
                successThreshold: 1
  - apiVersion: v1
    kind: Service
    metadata:
      name: petclinic
    spec:
      ports:
        - name: petclinic
          port: 8080
      selector:
        app.kubernetes.io/instance: petclinic-main
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: petclinic
    spec:
      host: petclinic-prj-elcavn-training-day.apps.okd.svc.elca.ch
      to:
        kind: Service
        name: petclinic
parameters:
  - name: CONTAINER_ID
